// ng-demo/src/app/app.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

import { DataService } from './data.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {

  private unsubscribe: Subject<void> = new Subject();
  users: any[];
  isLoading = true;
  newUser = {};

  constructor(private service: DataService) {

  }

  ngOnInit(): void {
    this.fetchData();
  }

  fetchData() {
    this.isLoading = true;
    const fetch = () => {
      this.service.getUsers()
        .pipe(
          takeUntil(this.unsubscribe)
        )
        .subscribe((res: any) => {
          this.users = res.data;
          this.isLoading = false;
        });
    };
    setTimeout(fetch, 1000);
  }

  handleChange(value) {
    this.newUser = {
      id: Math.max.apply(Math, this.users.map((u) => u.id + 1)),
      email: `${value}@reqres.in`,
      first_name: value,
      last_name: 'Surname',
      avatar: 'https://source.unsplash.com/random'
    };
  }

  handleSubmit(e) {
    this.users.push(this.newUser);
    e.preventDefault();
  }

  clearData() {
    this.users = [];
  }

  deleteUser(id: number) {
    this.users = this.users.filter(u => u.id !== id);
  }

  ngOnDestroy(): void {
    this.unsubscribe.next();
    this.unsubscribe.complete();
  }
}

<div class="container mt-5">
  <h1>Rest App</h1>

  <div class="spinner-border" role="status" *ngIf="isLoading">
    <span class="sr-only">Loading...</span>
  </div>

  <div *ngIf="!isLoading">
    <table class="table mt-5">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Identity</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let user of users">
          <td>{{user.first_name}} {{user.last_name}}</td>
          <td>{{user.email}}</td>
          <td><img src="{{user.avatar}}" class="avatar" alt="" /></td>
          <td><button class="btn btn-sm btn-primary" (click)="deleteUser(user.id)">Delete</button></td>
        </tr>
      </tbody>
    </table>
    <button class="btn btn-sm btn-primary mr-2" (click)="clearData()">Clear</button>
    <button class="btn btn-sm btn-primary" (click)="fetchData()">Fetch</button>

    <form class="mt-5" (submit)="handleSubmit($event)">
      <div>
        <input type="text" class="form-control" id="userName" placeholder="Name"
               (change)="handleChange($event.target.value)" />
      </div>
      <input type="submit" class="btn btn-sm btn-primary mt-2" value="Submit" />
    </form>

  </div>
</div>

// react-demo/src/App.js
import React, { useEffect, useState } from 'react';

import UserTable from './components/UserTable';
import { getUsers } from './services/DataService';

const App = () => {

  const [data, setData] = useState({ users: [], isLoading: true });

  const [newUser, setNewUser] = useState({});

  useEffect(() => {

    const fetchUsers = () => {
      getUsers().then(res => {
        if (!res) return;
        setData({ users: res.data.data, isLoading: false });
      });
    }
    setTimeout(fetchUsers, 1000);
    // eslint-disable-next-line
  }, [data.isLoading]);

  const renderIsLoading = () => {
    return (
      <div className="spinner-border" role="status">
        <span className="sr-only">Loading...</span>
      </div>
    )
  }

  const clearData = () => setData({ users: [], isLoading: data.isLoading });

  const fetchData = () => setData({ users: [], isLoading: true });

  const deleteUser = (id) => setData({ users: [...data.users.filter(u => u.id !== id)], isLoading: data.isLoading });

  const handleSubmit = (e) => {
    setData({ users: [...data.users, newUser], isLoading: data.isLoading });
    e.preventDefault();
  }

  const handleChange = (e) => {
    const value = e.target.value;
    const user = {
      id: Math.max.apply(Math, data.users.map((u) => u.id + 1)),
      email: `${value}@reqres.in`,
      first_name: value,
      last_name: 'Surname',
      avatar: 'https://source.unsplash.com/random'
    };
    setNewUser(user);
  }

  return (
    <div className="container mt-5">
      <h1>Rest App</h1>

      {data.isLoading ? renderIsLoading() : <UserTable data={data} deleteUser={deleteUser} fetchData={fetchData} clearData={clearData} />}

      {
        !data.isLoading && (
          <form className="mt-5" onSubmit={handleSubmit}>
            <div>
              <input type="text" className="form-control" id="userName" placeholder="Name" onChange={handleChange} />
            </div>
            <input type="submit" className="btn btn-sm btn-primary mt-2" value="Submit" />
          </form>)
      }
    </div>
  );
}

export default App;
